# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7bda75c32c474d176352a8d2c15dffe9ba37f9216f615f50a0f3adc71c933d1011662ecd83c9b4cae218dafe19c94ae879186e004a72fd0eb58c583950836926

test:
  secret_key_base: 0bf06db9fd3d456f35da54a343bff27a958c646948dfd439456dfbce13e1de30b17d6fbb5e89ffb62a107993f849996db9b94c29e52e73dbaf11485ebe5814a1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
